export const fruitsData = [
  {
    id: "1",
    product: "Brocolli ",
    image: "Assets/Vegitables/1.jpg",
    quantity: "1 ",
    price: "120.00",
  },
  {
    id: "2",
    product: "Cauliflower ",
    image: "Assets/Vegitables/2.jpg",
    quantity: "1 ",
    price: "60.00",
  },
  {
    id: "3",
    product: "Cucumber ",
    image: "Assets/Vegitables/3.jpg",
    quantity: "1 ",
    price: "48.00",
  },
  {
    id: "4",
    product: "Beetroot ",
    image: "Assets/Vegitables/4.jpg",
    quantity: "1 ",
    price: "32.00",
  },
  {
    id: "5",
    product: "Carrot ",
    image: "Assets/Vegitables/5.jpg",
    quantity: "1 ",
    price: "56.00",
  },
  {
    id: "6",
    product: "Tomato ",
    image: "Assets/Vegitables/6.jpg",
    quantity: "1 ",
    price: "16.00",
  },
  {
    id: "7",
    product: "Beans ",
    image: "Assets/Vegitables/7.jpg",
    quantity: "1 ",
    price: "82.00",
  },
  {
    id: "8",
    product: "Brinjal ",
    image: "Assets/Vegitables/8.jpg",
    quantity: "1 ",
    price: "35.00",
  },
  {
    id: "9",
    product: "Capsicum",
    image: "Assets/Vegitables/9.jpg",
    quantity: "1 ",
    price: "60.00",
  },
  {
    id: "10",
    product: "Mushroom ",
    image: "Assets/Vegitables/10.jpg",
    quantity: "1 ",
    price: "75.00",
  },
  {
    id: "11",
    product: "Potato ",
    image: "Assets/Vegitables/11.jpg",
    quantity: "1 ",
    price: "22.00",
  },
  {
    id: "12",
    product: "Pumpkin ",
    image: "/assets/Vegitables/12.jpg",
    quantity: "1 ",
    price: "48.00",
  },
  {
    id: "13",
    product: "Corn ",
    image: "Assets/Vegitables/13.jpg",
    quantity: "1 ",
    price: "75.00",
  },
  {
    id: "14",
    product: "Onion ",
    image: "Assets/Vegitables/14.jpg",
    quantity: "1 ",
    price: "16.00",
  },

  {
    id: "15",
    product: "Apple",
    image: "Assets/Fruits/1.jpg",
    quantity: "1 ",
    price: "72.00",
  },
  {
    id: "16",
    product: "Banana",
    image: "Assets/Fruits/2.jpg",
    quantity: "1 ",
    price: "45.00",
  },
  {
    id: "17",
    product: "Grapes",
    image: "Assets/Fruits/3.jpg",
    quantity: "1 ",
    price: "60.00",
  },
  {
    id: "18",
    product: "Mango",
    image: "Assets/Fruits/4.jpg",
    quantity: "1 ",
    price: "75.00",
  },
  {
    id: "19",
    product: "MuskMelon",
    image: "Assets/Fruits/5.jpg",
    quantity: "1 ",
    price: "60.00",
  },
  {
    id: "20",
    product: "Orange",
    image: "Assets/Fruits/6.jpg",
    quantity: "1 ",
    price: "75.00",
  },
  {
    id: "21",
    product: "Pears",
    image: "Assets/Fruits/7.jpg",
    quantity: "1 ",
    price: "69.00",
  },
  {
    id: "22",
    product: "Pomogranate",
    image: "Assets/Fruits/8.jpg",
    quantity: "1 ",
    price: "95.00",
  },
  {
    id: "23",
    product: "Raspberry",
    image: "Assets/Fruits/9.jpg",
    quantity: "1 ",
    price: "160.00",
  },
  {
    id: "24",
    product: "StrawBerry",
    image: "Assets/Fruits/10.jpg",
    quantity: "1 ",
    price: "180.00",
  },
  {
    id: "25",
    product: "WaterMelon",
    image: "Assets/Fruits/11.jpg",
    quantity: "1 ",
    price: "28.00",
  },

  {
    id: "26",
    product: "Almonds ",
    image: "Assets/Dryfruits/1.jpg",
    quantity: "1 ",
    price: "72.00",
  },
  {
    id: "27",
    product: "Pista  ",
    image: "Assets/Dryfruits/2.jpg",
    quantity: "1 ",
    price: "45.00",
  },
  {
    id: "28",
    product: "Nuts Mixture  ",
    image: "Assets/Dryfruits/3.jpg",
    quantity: "1 ",
    price: "45.00",
  },
  {
    id: "29",
    product: "Cashews  ",
    image: "Assets/Dryfruits/4.jpg",
    quantity: "1 ",
    price: "45.00",
  },
  {
    id: "30",
    product: "Walnuts  ",
    image: "Assets/Dryfruits/5.jpg",
    quantity: "1 ",
    price: "45.00",
  },
];
